# Generated by Django 5.2.10 on 2026-02-11 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshcut', '0003_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
